spring:
  application:
    name: Library Events Producer
---
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "library-events"
    producer:
      bootstrap-servers:
        - localhost:9091
        - localhost:9092
        - localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        ack: -1
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap-servers:
          - localhost:9091
          - localhost:9092
          - localhost:909
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      bootstrap-servers: dev:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer